server:
  port: 8888
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: /META-INF/maven, /META-INF/resources, /resources, /static, /public, /templates